In [1]:
# import libraries (you may add additional imports but you may not have to)
import numpy as np
import pandas as pd
from scipy.sparse import csr_matrix
from sklearn.neighbors import NearestNeighbors
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
# get data files
!wget https://cdn.freecodecamp.org/project-data/books/book-crossings.zip

!unzip book-crossings.zip

books_filename = 'BX-Books.csv'
ratings_filename = 'BX-Book-Ratings.csv'

--2025-06-19 18:35:58--  https://cdn.freecodecamp.org/project-data/books/book-crossings.zip
Resolving cdn.freecodecamp.org (cdn.freecodecamp.org)... 172.67.70.149, 104.26.3.33, 104.26.2.33, ...
Connecting to cdn.freecodecamp.org (cdn.freecodecamp.org)|172.67.70.149|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 26085508 (25M) [application/zip]
Saving to: ‘book-crossings.zip’

book-crossings.zip  100%[===================>]  24.88M   144MB/s    in 0.2s

2025-06-19 18:35:58 (144 MB/s) - ‘book-crossings.zip’ saved [26085508/26085508]

Archive:  book-crossings.zip
  inflating: BX-Book-Ratings.csv
  inflating: BX-Books.csv
  inflating: BX-Users.csv

In [3]:
# import csv data into dataframes
df_books = pd.read_csv(
    books_filename,
    encoding = "ISO-8859-1",
    sep=";",
    header=0,
    names=['isbn', 'title', 'author'],
    usecols=['isbn', 'title', 'author'],
    dtype={'isbn': 'str', 'title': 'str', 'author': 'str'})

df_ratings = pd.read_csv(
    ratings_filename,
    encoding = "ISO-8859-1",
    sep=";",
    header=0,
    names=['user', 'isbn', 'rating'],
    usecols=['user', 'isbn', 'rating'],
    dtype={'user': 'int32', 'isbn': 'str', 'rating': 'float32'})

In [98]:
df_books

,isbn,title,author
0,0195153448,Classical Mythology,Mark P. O. Morford
1,0002005018,Clara Callan,Richard Bruce Wright
2,0060973129,Decision in Normandy,Carlo D'Este
3,0374157065,Flu: The Story of the Great Influenza Pandemic...,Gina Bari Kolata
4,0393045218,The Mummies of Urumchi,E. J. W. Barber
...,...,...,...
271374,0440400988,There's a Bat in Bunk Five,Paula Danziger
271375,0525447644,From One to One Hundred,Teri Sloat
271376,006008667X,Lily Dale : The True Story of the Town that Ta...,Christine Wicker
271377,0192126040,Republic (World's Classics),Plato
271378,0767409752,A Guided Tour of Rene Descartes' Meditations o...,Christopher Biffle

In [139]:

df_books_merge_rate = pd.merge(df_books, df_ratings, on="isbn")
ratings_per_book = df_books_merge_rate.groupby(['title'])['rating'].count()
filtered_books = ratings_per_book[ratings_per_book > 99]
filtered_books

title
1984                                                                 284
1st to Die: A Novel                                                  509
24 Hours                                                             106
2nd Chance                                                           356
4 Blondes                                                            151
                                                                    ...
Year of Wonders                                                      169
You Belong To Me                                                     123
Zen and the Art of Motorcycle Maintenance: An Inquiry into Values    210
Zoya                                                                 103
\O\" Is for Outlaw"                                                  269
Name: rating, Length: 914, dtype: int64

In [122]:
df_books_merge_rate
user_rates = df_books_merge_rate.groupby(['user'])['rating'].sum()
filtered_users = user_rates[user_rates > 199]
filtered_users

user
254       443.0
507       296.0
638       501.0
643       335.0
882       345.0
          ...
278221    213.0
278356    293.0
278418    641.0
278582    275.0
278633    312.0
Name: rating, Length: 2434, dtype: float32

In [140]:
df_filtered = df_books_merge_rate[
    (df_books_merge_rate['user'].isin(filtered_users.index)) &
    (df_books_merge_rate['title'].isin(filtered_books.index))
]
df_filtered

,isbn,title,author,user,rating
31,0399135782,The Kitchen God's Wife,Amy Tan,11676,9.0
32,0399135782,The Kitchen God's Wife,Amy Tan,29526,9.0
33,0399135782,The Kitchen God's Wife,Amy Tan,36836,0.0
34,0399135782,The Kitchen God's Wife,Amy Tan,46398,9.0
38,0399135782,The Kitchen God's Wife,Amy Tan,113270,0.0
...,...,...,...,...,...
1028639,0394429869,I Know Why the Caged Bird Sings,Maya Angelou,239594,8.0
1028854,0743527631,The Pillars of the Earth,Ken Follett,240144,0.0
1028856,0745168086,The Handmaid's Tale,Margaret Atwood,240144,0.0
1030533,0553290703,Lightning,Patricia Potter,244685,9.0
1031021,0395647398,"The Two Towers (The Lord of the Rings, Part 2)",J. R. R. Tolkien,259901,10.0

In [ ]:
# function to return recommended books - this will be tested
def get_recommends(book = ""):


  return recommended_books

In [ ]:
books = get_recommends("Where the Heart Is (Oprah's Book Club (Paperback))")
print(books)

def test_book_recommendation():
  test_pass = True
  recommends = get_recommends("Where the Heart Is (Oprah's Book Club (Paperback))")
  if recommends[0] != "Where the Heart Is (Oprah's Book Club (Paperback))":
    test_pass = False
  recommended_books = ["I'll Be Seeing You", 'The Weight of Water', 'The Surgeon', 'I Know This Much Is True']
  recommended_books_dist = [0.8, 0.77, 0.77, 0.77]
  for i in range(2):
    if recommends[1][i][0] not in recommended_books:
      test_pass = False
    if abs(recommends[1][i][1] - recommended_books_dist[i]) >= 0.05:
      test_pass = False
  if test_pass:
    print("You passed the challenge! 🎉🎉🎉🎉🎉")
  else:
    print("You haven't passed yet. Keep trying!")

test_book_recommendation()